name: Review Deployment

on:

  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: ${{ vars.FLY_REGION || 'sin' }}
  FLY_ORG: ${{ vars.FLY_ORG || 'personal' }}
  APP_NAME: pr-${{ github.event.pull_request.number }}-cybersieve

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filter.yaml

  test-specified:
    if: ${{ github.event.action != 'closed' }}
    needs: filter
    uses: ./.github/workflows/test.yaml
    with:
      services: ${{ needs.filter.outputs.services }}
    secrets: inherit

  review-backend:
    if: ${{ needs.filter.outputs.services == 'backend' && github.event.action != 'closed' && needs.filter.outputs.services != '[]' && needs.filter.outputs.services != ''}}
    runs-on: ubuntu-latest
    needs: [filter, test-specified]
    concurrency:
      group: pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.filter.outputs.services) }}
    environment:
      name: pr-${{ github.event.pull_request.number }}
      url: https://${{ env.APP_NAME }}.fly.dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup fly
        if: ${{ matrix.service == 'backend' }}
        uses: superfly/fly-pr-review-apps@f7152c133b1fe7767b6e549ca09598655c1f8ca4
        with:
          name: ${{ env.APP_NAME }}
          path: backend
          secrets: >
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            JWKS_URL=${{ secrets.JWKS_URL }}
            AUDIENCE=${{ secrets.AUDIENCE }}
            ALGORITHM=${{ secrets.ALGORITHM }}

  review-frontend:
    if: ${{ needs.filter.outputs.services == 'frontend' && github.event.action != 'closed' && needs.filter.outputs.services != '[]' && needs.filter.outputs.services != ''}}
    runs-on: ubuntu-latest
    needs: [filter, test-specified]
    environment:
      name: pr-${{ github.event.pull_request.number }}
      url: ${{ steps.vercel-deploy.outputs.deployment_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: vercel-deploy
        run: |
          deployment_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "deployment_url=$deployment_url" >> $GITHUB_OUTPUT

  review-cleanup:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    needs: filter
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ contains(needs.filter.outputs.services, 'backend') }}
      - name: Destroy Fly App
        if: ${{ contains(needs.filter.outputs.services, 'backend') }}
        run: flyctl apps destroy ${{ env.APP_NAME }} --yes
        continue-on-error: true

      - name: Delete GitHub Environment
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
        with:
          token: ${{ secrets.GH_PAT }}
          environment: pr-${{ github.event.pull_request.number }}
          onlyRemoveDeployments: false