name: Review Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]


env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: ${{ vars.FLY_REGION || 'sin' }}
  FLY_ORG: ${{ vars.FLY_ORG || 'personal' }}

jobs:
  test-app:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  filter:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filter.yaml

  review-deploy:
    runs-on: ubuntu-latest
    needs: [filter, test-app]
    # Handle empty list
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.filter.outputs.services) }}
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.pull_request.number }}
    
    environment:
      name: pr-${{ github.event.pull_request.number }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup fly
        id: deploy
        if: ${{ matrix.service == 'backend' }}
        uses: superfly/fly-pr-review-apps@f7152c133b1fe7767b6e549ca09598655c1f8ca4
        with:
          name: pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}
          path: backend
          secrets: >
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            JWKS_URL=${{ secrets.JWKS_URL }}
            AUDIENCE=${{ secrets.AUDIENCE }}
            ALGORITHM=${{ secrets.ALGORITHM }}

  review-cleanup:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    needs: review-deploy
    
    permissions:
      deployments: write
      contents: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Delete GitHub Environment
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
        with:
          token: ${{ secrets.GH_PAT }}
          environment: pr-${{ github.event.pull_request.number }}
          onlyRemoveDeployments: false