name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      service:
        description: 'Select the service to deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - backend
          - frontend

concurrency:
  group: deploy
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEPLOY }}

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filter.yaml

  deploy-backend:
    if: ${{ contains(needs.filter.outputs.services, 'backend') }}
    needs: [filter]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # v1.5
      - run: |
          flyctl secrets set \
            DB_USER="${{ secrets.DB_USER }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            DB_HOST="${{ secrets.DB_HOST }}" \
            DB_PORT="${{ secrets.DB_PORT }}" \
            DB_NAME="${{ secrets.DB_NAME }}" \
            SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            SUPABASE_KEY="${{ secrets.SUPABASE_KEY }}" \
            JWKS_URL="${{ secrets.JWKS_URL }}" \
            AUDIENCE="${{ secrets.AUDIENCE }}" \
            ALGORITHM="${{ secrets.ALGORITHM }}" \
            --stage
          flyctl deploy --remote-only

  deploy-frontend:
    if: ${{ contains(needs.filter.outputs.services, 'frontend') }}
    needs: [filter]
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TELEMETRY_DISABLED: 1
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_PUBLISHABLE_OR_ANON_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_OR_ANON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Use Node.js 24
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24

      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}