name: Review Deployment to Fly.io

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Fly.io App Name'
        type: string

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: ${{ vars.FLY_REGION || 'sin' }}
  FLY_ORG: ${{ vars.FLY_ORG || 'personal' }}

jobs:
  review-deploy:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    
    environment:
      name: ${{ inputs.app-name }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup fly
        id: deploy
        uses: superfly/fly-pr-review-apps@f7152c133b1fe7767b6e549ca09598655c1f8ca4
        with:
          name: ${{ inputs.app-name }}