name: Review Deployment to Fly.io

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]


env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: ${{ vars.FLY_REGION || 'sin' }}
  FLY_ORG: ${{ vars.FLY_ORG || 'personal' }}

jobs:
  review-deploy:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.pull_request.number }}
    
    environment:
      name: pr-${{ github.event.pull_request.number }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup fly
        id: deploy
        uses: superfly/fly-pr-review-apps@f7152c133b1fe7767b6e549ca09598655c1f8ca4
        with:
          name: pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}
          path: backend
          secrets: >
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            JWKS_URL=${{ secrets.JWKS_URL }}
            AUDIENCE=${{ secrets.AUDIENCE }}
            ALGORITHM=${{ secrets.ALGORITHM }}

  review-cleanup:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    needs: review-deploy
    
    permissions:
      deployments: write
      contents: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Delete GitHub Environment
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
        with:
          token: ${{ secrets.GH_PAT }}
          environment: pr-${{ github.event.pull_request.number }}
          onlyRemoveDeployments: false