name: Review Deployment to Fly.io

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]


env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: ${{ vars.FLY_REGION || 'sin' }}
  FLY_ORG: ${{ vars.FLY_ORG || 'personal' }}

jobs:
  review-deploy:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.pull_request.number }}
    
    environment:
      name: pr-${{ github.event.pull_request.number }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup fly
        id: deploy
        uses: superfly/fly-pr-review-apps@f7152c133b1fe7767b6e549ca09598655c1f8ca4
        with:
          name: pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}
          path: backend