name: Run tests

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Folders to test'
        required: false
        type: choice
        default: '' 
        options:
          - backend
          - frontend
  workflow_call:
    inputs:
      services:
        description: 'Folders to test'
        required: false
        type: string

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.final.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Auto-detect changes
        id: filter
        if: ${{ inputs.services == '' }}
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        with:
          filters: .github/utils/file-filter.yaml

      - name: Determine Services to Test
        id: final
        run: |
          MANUAL_INPUT='${{ inputs.services }}'
          AUTO_DETECT='${{ steps.filter.outputs.changes }}'
          if [ -n "$MANUAL_INPUT" ] && [ "$MANUAL_INPUT" != "[]" ]; then
            echo "✅ Using Manual Input"
            # If input doesn't start with [, wrap it in [] to make it a valid JSON array
            if [[ "$MANUAL_INPUT" != \[* ]]; then
              MANUAL_INPUT="[\"$MANUAL_INPUT\"]"
            fi
            echo "result=$MANUAL_INPUT" >> $GITHUB_OUTPUT
          elif [ -n "$AUTO_DETECT" ] && [ "$AUTO_DETECT" != "[]" ]; then
            echo "✅ Using Auto Detect"
            echo "result=$AUTO_DETECT" >> $GITHUB_OUTPUT
          else
            echo "⚠️ No changes or inputs detected"
            echo "result=[]" >> $GITHUB_OUTPUT
          fi

  tests:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.filter.outputs.services) }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Python (Backend)
        if: ${{ matrix.service == 'backend' }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: backend/pyproject.toml
          
      - name: Install uv (Backend)
        if: ${{ matrix.service == 'backend' }}
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true

      - name: Setup Node (Frontend)
        if: ${{ matrix.service == 'frontend' }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: frontend/package.json
          cache: npm
          cache-dependency-path: frontend/package.json

      - name: Install Task
        uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217 
        with:
          uri: https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.tar.gz
          name: task
          version: v3.45.5

      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: |
          task install-ci

      - name: Run Tests
        working-directory: ${{ matrix.service }}
        run: |
          task tests